# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'vtn_principal.ui'
##
## Created by: Qt User Interface Compiler version 6.5.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDateEdit, QLabel,
    QLineEdit, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QSpinBox, QStatusBar, QWidget)

class Ui_vtn_principal(object):
    def setupUi(self, vtn_principal):
        if not vtn_principal.objectName():
            vtn_principal.setObjectName(u"vtn_principal")
        vtn_principal.resize(619, 701)
        palette = QPalette()
        brush = QBrush(QColor(85, 0, 127, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(255, 170, 255, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(255, 255, 255, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush3 = QBrush(QColor(255, 212, 255, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        brush4 = QBrush(QColor(127, 85, 127, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush4)
        brush5 = QBrush(QColor(170, 113, 170, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        brush6 = QBrush(QColor(0, 0, 0, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        brush7 = QBrush(QColor(255, 255, 220, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush6)
        vtn_principal.setPalette(palette)
        font = QFont()
        font.setPointSize(8)
        font.setBold(True)
        vtn_principal.setFont(font)
        self.centralwidget = QWidget(vtn_principal)
        self.centralwidget.setObjectName(u"centralwidget")
        self.lbl_nombre = QLabel(self.centralwidget)
        self.lbl_nombre.setObjectName(u"lbl_nombre")
        self.lbl_nombre.setGeometry(QRect(40, 140, 71, 16))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush8 = QBrush(QColor(49, 0, 74, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush8)
        brush9 = QBrush(QColor(73, 0, 111, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Light, brush9)
        brush10 = QBrush(QColor(61, 0, 92, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Midlight, brush10)
        brush11 = QBrush(QColor(24, 0, 37, 255))
        brush11.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Dark, brush11)
        brush12 = QBrush(QColor(32, 0, 49, 255))
        brush12.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Mid, brush12)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette1.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush8)
        palette1.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette1.setBrush(QPalette.Active, QPalette.AlternateBase, brush11)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipBase, brush7)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush8)
        palette1.setBrush(QPalette.Inactive, QPalette.Light, brush9)
        palette1.setBrush(QPalette.Inactive, QPalette.Midlight, brush10)
        palette1.setBrush(QPalette.Inactive, QPalette.Dark, brush11)
        palette1.setBrush(QPalette.Inactive, QPalette.Mid, brush12)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette1.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush11)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush7)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush6)
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush11)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush8)
        palette1.setBrush(QPalette.Disabled, QPalette.Light, brush9)
        palette1.setBrush(QPalette.Disabled, QPalette.Midlight, brush10)
        palette1.setBrush(QPalette.Disabled, QPalette.Dark, brush11)
        palette1.setBrush(QPalette.Disabled, QPalette.Mid, brush12)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush11)
        palette1.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush11)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush8)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush8)
        palette1.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        palette1.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush8)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush7)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush6)
        self.lbl_nombre.setPalette(palette1)
        font1 = QFont()
        font1.setFamilies([u"Perpetua Titling MT"])
        font1.setBold(True)
        self.lbl_nombre.setFont(font1)
        self.lbl_apellido = QLabel(self.centralwidget)
        self.lbl_apellido.setObjectName(u"lbl_apellido")
        self.lbl_apellido.setGeometry(QRect(40, 190, 71, 16))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush8)
        palette2.setBrush(QPalette.Active, QPalette.Light, brush9)
        palette2.setBrush(QPalette.Active, QPalette.Midlight, brush10)
        palette2.setBrush(QPalette.Active, QPalette.Dark, brush11)
        palette2.setBrush(QPalette.Active, QPalette.Mid, brush12)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette2.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush2)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush8)
        palette2.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette2.setBrush(QPalette.Active, QPalette.AlternateBase, brush11)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipBase, brush7)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush8)
        palette2.setBrush(QPalette.Inactive, QPalette.Light, brush9)
        palette2.setBrush(QPalette.Inactive, QPalette.Midlight, brush10)
        palette2.setBrush(QPalette.Inactive, QPalette.Dark, brush11)
        palette2.setBrush(QPalette.Inactive, QPalette.Mid, brush12)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.ButtonText, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette2.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette2.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush11)
        palette2.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush7)
        palette2.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush6)
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush11)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush8)
        palette2.setBrush(QPalette.Disabled, QPalette.Light, brush9)
        palette2.setBrush(QPalette.Disabled, QPalette.Midlight, brush10)
        palette2.setBrush(QPalette.Disabled, QPalette.Dark, brush11)
        palette2.setBrush(QPalette.Disabled, QPalette.Mid, brush12)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush11)
        palette2.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush11)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush8)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush8)
        palette2.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        palette2.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush8)
        palette2.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush7)
        palette2.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush6)
        self.lbl_apellido.setPalette(palette2)
        self.lbl_apellido.setFont(font1)
        self.btn_grabar = QPushButton(self.centralwidget)
        self.btn_grabar.setObjectName(u"btn_grabar")
        self.btn_grabar.setGeometry(QRect(250, 580, 93, 61))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush6)
        brush13 = QBrush(QColor(170, 85, 255, 255))
        brush13.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.Button, brush13)
        brush14 = QBrush(QColor(234, 213, 255, 255))
        brush14.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.Light, brush14)
        brush15 = QBrush(QColor(202, 149, 255, 255))
        brush15.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.Midlight, brush15)
        brush16 = QBrush(QColor(85, 42, 127, 255))
        brush16.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.Dark, brush16)
        brush17 = QBrush(QColor(113, 56, 170, 255))
        brush17.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.Mid, brush17)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush6)
        palette3.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette3.setBrush(QPalette.Active, QPalette.ButtonText, brush6)
        palette3.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette3.setBrush(QPalette.Active, QPalette.Window, brush13)
        palette3.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        brush18 = QBrush(QColor(212, 170, 255, 255))
        brush18.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.AlternateBase, brush18)
        palette3.setBrush(QPalette.Active, QPalette.ToolTipBase, brush7)
        palette3.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush13)
        palette3.setBrush(QPalette.Inactive, QPalette.Light, brush14)
        palette3.setBrush(QPalette.Inactive, QPalette.Midlight, brush15)
        palette3.setBrush(QPalette.Inactive, QPalette.Dark, brush16)
        palette3.setBrush(QPalette.Inactive, QPalette.Mid, brush17)
        palette3.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        palette3.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.ButtonText, brush6)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush13)
        palette3.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette3.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush18)
        palette3.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush7)
        palette3.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush6)
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush16)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush13)
        palette3.setBrush(QPalette.Disabled, QPalette.Light, brush14)
        palette3.setBrush(QPalette.Disabled, QPalette.Midlight, brush15)
        palette3.setBrush(QPalette.Disabled, QPalette.Dark, brush16)
        palette3.setBrush(QPalette.Disabled, QPalette.Mid, brush17)
        palette3.setBrush(QPalette.Disabled, QPalette.Text, brush16)
        palette3.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette3.setBrush(QPalette.Disabled, QPalette.ButtonText, brush16)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush13)
        palette3.setBrush(QPalette.Disabled, QPalette.Window, brush13)
        palette3.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        palette3.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush13)
        palette3.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush7)
        palette3.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush6)
        self.btn_grabar.setPalette(palette3)
        font2 = QFont()
        font2.setFamilies([u"Terminal"])
        font2.setBold(True)
        self.btn_grabar.setFont(font2)
        self.cb_tipo_persona = QComboBox(self.centralwidget)
        self.cb_tipo_persona.addItem("")
        self.cb_tipo_persona.addItem("")
        self.cb_tipo_persona.setObjectName(u"cb_tipo_persona")
        self.cb_tipo_persona.setGeometry(QRect(150, 80, 221, 31))
        palette4 = QPalette()
        brush19 = QBrush(QColor(170, 0, 127, 255))
        brush19.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush19)
        palette4.setBrush(QPalette.Active, QPalette.Text, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush19)
        palette4.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette4.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        self.cb_tipo_persona.setPalette(palette4)
        self.lbl_tipo_persona = QLabel(self.centralwidget)
        self.lbl_tipo_persona.setObjectName(u"lbl_tipo_persona")
        self.lbl_tipo_persona.setGeometry(QRect(40, 90, 55, 16))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Active, QPalette.Button, brush8)
        palette5.setBrush(QPalette.Active, QPalette.Light, brush9)
        palette5.setBrush(QPalette.Active, QPalette.Midlight, brush10)
        palette5.setBrush(QPalette.Active, QPalette.Dark, brush11)
        palette5.setBrush(QPalette.Active, QPalette.Mid, brush12)
        palette5.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette5.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette5.setBrush(QPalette.Active, QPalette.ButtonText, brush2)
        palette5.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette5.setBrush(QPalette.Active, QPalette.Window, brush8)
        palette5.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette5.setBrush(QPalette.Active, QPalette.AlternateBase, brush11)
        palette5.setBrush(QPalette.Active, QPalette.ToolTipBase, brush7)
        palette5.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.Button, brush8)
        palette5.setBrush(QPalette.Inactive, QPalette.Light, brush9)
        palette5.setBrush(QPalette.Inactive, QPalette.Midlight, brush10)
        palette5.setBrush(QPalette.Inactive, QPalette.Dark, brush11)
        palette5.setBrush(QPalette.Inactive, QPalette.Mid, brush12)
        palette5.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.ButtonText, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette5.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette5.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette5.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush11)
        palette5.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush7)
        palette5.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush6)
        palette5.setBrush(QPalette.Disabled, QPalette.WindowText, brush11)
        palette5.setBrush(QPalette.Disabled, QPalette.Button, brush8)
        palette5.setBrush(QPalette.Disabled, QPalette.Light, brush9)
        palette5.setBrush(QPalette.Disabled, QPalette.Midlight, brush10)
        palette5.setBrush(QPalette.Disabled, QPalette.Dark, brush11)
        palette5.setBrush(QPalette.Disabled, QPalette.Mid, brush12)
        palette5.setBrush(QPalette.Disabled, QPalette.Text, brush11)
        palette5.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette5.setBrush(QPalette.Disabled, QPalette.ButtonText, brush11)
        palette5.setBrush(QPalette.Disabled, QPalette.Base, brush8)
        palette5.setBrush(QPalette.Disabled, QPalette.Window, brush8)
        palette5.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        palette5.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush8)
        palette5.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush7)
        palette5.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush6)
        self.lbl_tipo_persona.setPalette(palette5)
        self.lbl_tipo_persona.setFont(font1)
        self.txt_nombre = QLineEdit(self.centralwidget)
        self.txt_nombre.setObjectName(u"txt_nombre")
        self.txt_nombre.setGeometry(QRect(150, 130, 241, 41))
        self.txt_nombre.setMaxLength(50)
        self.txt_apellido = QLineEdit(self.centralwidget)
        self.txt_apellido.setObjectName(u"txt_apellido")
        self.txt_apellido.setGeometry(QRect(150, 180, 241, 41))
        self.txt_apellido.setMaxLength(50)
        self.txt_email = QLineEdit(self.centralwidget)
        self.txt_email.setObjectName(u"txt_email")
        self.txt_email.setGeometry(QRect(150, 290, 241, 41))
        self.txt_email.setMaxLength(100)
        self.lbl_email = QLabel(self.centralwidget)
        self.lbl_email.setObjectName(u"lbl_email")
        self.lbl_email.setGeometry(QRect(40, 300, 61, 16))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Active, QPalette.Button, brush8)
        palette6.setBrush(QPalette.Active, QPalette.Light, brush9)
        palette6.setBrush(QPalette.Active, QPalette.Midlight, brush10)
        palette6.setBrush(QPalette.Active, QPalette.Dark, brush11)
        palette6.setBrush(QPalette.Active, QPalette.Mid, brush12)
        palette6.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette6.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette6.setBrush(QPalette.Active, QPalette.ButtonText, brush2)
        palette6.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette6.setBrush(QPalette.Active, QPalette.Window, brush8)
        palette6.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette6.setBrush(QPalette.Active, QPalette.AlternateBase, brush11)
        palette6.setBrush(QPalette.Active, QPalette.ToolTipBase, brush7)
        palette6.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.Button, brush8)
        palette6.setBrush(QPalette.Inactive, QPalette.Light, brush9)
        palette6.setBrush(QPalette.Inactive, QPalette.Midlight, brush10)
        palette6.setBrush(QPalette.Inactive, QPalette.Dark, brush11)
        palette6.setBrush(QPalette.Inactive, QPalette.Mid, brush12)
        palette6.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette6.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette6.setBrush(QPalette.Inactive, QPalette.ButtonText, brush2)
        palette6.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette6.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette6.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette6.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush11)
        palette6.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush7)
        palette6.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush6)
        palette6.setBrush(QPalette.Disabled, QPalette.WindowText, brush11)
        palette6.setBrush(QPalette.Disabled, QPalette.Button, brush8)
        palette6.setBrush(QPalette.Disabled, QPalette.Light, brush9)
        palette6.setBrush(QPalette.Disabled, QPalette.Midlight, brush10)
        palette6.setBrush(QPalette.Disabled, QPalette.Dark, brush11)
        palette6.setBrush(QPalette.Disabled, QPalette.Mid, brush12)
        palette6.setBrush(QPalette.Disabled, QPalette.Text, brush11)
        palette6.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette6.setBrush(QPalette.Disabled, QPalette.ButtonText, brush11)
        palette6.setBrush(QPalette.Disabled, QPalette.Base, brush8)
        palette6.setBrush(QPalette.Disabled, QPalette.Window, brush8)
        palette6.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        palette6.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush8)
        palette6.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush7)
        palette6.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush6)
        self.lbl_email.setPalette(palette6)
        self.lbl_email.setFont(font1)
        self.lbl_Cedula = QLabel(self.centralwidget)
        self.lbl_Cedula.setObjectName(u"lbl_Cedula")
        self.lbl_Cedula.setGeometry(QRect(40, 250, 61, 16))
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette7.setBrush(QPalette.Active, QPalette.Button, brush8)
        palette7.setBrush(QPalette.Active, QPalette.Light, brush9)
        palette7.setBrush(QPalette.Active, QPalette.Midlight, brush10)
        palette7.setBrush(QPalette.Active, QPalette.Dark, brush11)
        palette7.setBrush(QPalette.Active, QPalette.Mid, brush12)
        palette7.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette7.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette7.setBrush(QPalette.Active, QPalette.ButtonText, brush2)
        palette7.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette7.setBrush(QPalette.Active, QPalette.Window, brush8)
        palette7.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette7.setBrush(QPalette.Active, QPalette.AlternateBase, brush11)
        palette7.setBrush(QPalette.Active, QPalette.ToolTipBase, brush7)
        palette7.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
        palette7.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.Button, brush8)
        palette7.setBrush(QPalette.Inactive, QPalette.Light, brush9)
        palette7.setBrush(QPalette.Inactive, QPalette.Midlight, brush10)
        palette7.setBrush(QPalette.Inactive, QPalette.Dark, brush11)
        palette7.setBrush(QPalette.Inactive, QPalette.Mid, brush12)
        palette7.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette7.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette7.setBrush(QPalette.Inactive, QPalette.ButtonText, brush2)
        palette7.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette7.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette7.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette7.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush11)
        palette7.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush7)
        palette7.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush6)
        palette7.setBrush(QPalette.Disabled, QPalette.WindowText, brush11)
        palette7.setBrush(QPalette.Disabled, QPalette.Button, brush8)
        palette7.setBrush(QPalette.Disabled, QPalette.Light, brush9)
        palette7.setBrush(QPalette.Disabled, QPalette.Midlight, brush10)
        palette7.setBrush(QPalette.Disabled, QPalette.Dark, brush11)
        palette7.setBrush(QPalette.Disabled, QPalette.Mid, brush12)
        palette7.setBrush(QPalette.Disabled, QPalette.Text, brush11)
        palette7.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette7.setBrush(QPalette.Disabled, QPalette.ButtonText, brush11)
        palette7.setBrush(QPalette.Disabled, QPalette.Base, brush8)
        palette7.setBrush(QPalette.Disabled, QPalette.Window, brush8)
        palette7.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        palette7.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush8)
        palette7.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush7)
        palette7.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush6)
        self.lbl_Cedula.setPalette(palette7)
        self.lbl_Cedula.setFont(font1)
        self.txt_cedula = QLineEdit(self.centralwidget)
        self.txt_cedula.setObjectName(u"txt_cedula")
        self.txt_cedula.setGeometry(QRect(150, 240, 241, 41))
        self.txt_cedula.setMaxLength(10)
        self.btn_buscar_cedula = QPushButton(self.centralwidget)
        self.btn_buscar_cedula.setObjectName(u"btn_buscar_cedula")
        self.btn_buscar_cedula.setGeometry(QRect(410, 250, 161, 28))
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.Text, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette8.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        self.btn_buscar_cedula.setPalette(palette8)
        self.lbl_estatura = QLabel(self.centralwidget)
        self.lbl_estatura.setObjectName(u"lbl_estatura")
        self.lbl_estatura.setGeometry(QRect(20, 410, 111, 20))
        palette9 = QPalette()
        palette9.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette9.setBrush(QPalette.Active, QPalette.Button, brush8)
        palette9.setBrush(QPalette.Active, QPalette.Light, brush9)
        palette9.setBrush(QPalette.Active, QPalette.Midlight, brush10)
        palette9.setBrush(QPalette.Active, QPalette.Dark, brush11)
        palette9.setBrush(QPalette.Active, QPalette.Mid, brush12)
        palette9.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette9.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette9.setBrush(QPalette.Active, QPalette.ButtonText, brush2)
        palette9.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette9.setBrush(QPalette.Active, QPalette.Window, brush8)
        palette9.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette9.setBrush(QPalette.Active, QPalette.AlternateBase, brush11)
        palette9.setBrush(QPalette.Active, QPalette.ToolTipBase, brush7)
        palette9.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
        palette9.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette9.setBrush(QPalette.Inactive, QPalette.Button, brush8)
        palette9.setBrush(QPalette.Inactive, QPalette.Light, brush9)
        palette9.setBrush(QPalette.Inactive, QPalette.Midlight, brush10)
        palette9.setBrush(QPalette.Inactive, QPalette.Dark, brush11)
        palette9.setBrush(QPalette.Inactive, QPalette.Mid, brush12)
        palette9.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette9.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette9.setBrush(QPalette.Inactive, QPalette.ButtonText, brush2)
        palette9.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette9.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette9.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette9.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush11)
        palette9.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush7)
        palette9.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush6)
        palette9.setBrush(QPalette.Disabled, QPalette.WindowText, brush11)
        palette9.setBrush(QPalette.Disabled, QPalette.Button, brush8)
        palette9.setBrush(QPalette.Disabled, QPalette.Light, brush9)
        palette9.setBrush(QPalette.Disabled, QPalette.Midlight, brush10)
        palette9.setBrush(QPalette.Disabled, QPalette.Dark, brush11)
        palette9.setBrush(QPalette.Disabled, QPalette.Mid, brush12)
        palette9.setBrush(QPalette.Disabled, QPalette.Text, brush11)
        palette9.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette9.setBrush(QPalette.Disabled, QPalette.ButtonText, brush11)
        palette9.setBrush(QPalette.Disabled, QPalette.Base, brush8)
        palette9.setBrush(QPalette.Disabled, QPalette.Window, brush8)
        palette9.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        palette9.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush8)
        palette9.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush7)
        palette9.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush6)
        self.lbl_estatura.setPalette(palette9)
        self.lbl_estatura.setFont(font1)
        self.sp_estatura = QSpinBox(self.centralwidget)
        self.sp_estatura.setObjectName(u"sp_estatura")
        self.sp_estatura.setGeometry(QRect(150, 400, 81, 31))
        self.sp_estatura.setMaximum(300)
        self.btn_estatura = QPushButton(self.centralwidget)
        self.btn_estatura.setObjectName(u"btn_estatura")
        self.btn_estatura.setGeometry(QRect(390, 400, 151, 31))
        self.lbl_peso = QLabel(self.centralwidget)
        self.lbl_peso.setObjectName(u"lbl_peso")
        self.lbl_peso.setGeometry(QRect(20, 460, 111, 20))
        palette10 = QPalette()
        palette10.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette10.setBrush(QPalette.Active, QPalette.Button, brush8)
        palette10.setBrush(QPalette.Active, QPalette.Light, brush9)
        palette10.setBrush(QPalette.Active, QPalette.Midlight, brush10)
        palette10.setBrush(QPalette.Active, QPalette.Dark, brush11)
        palette10.setBrush(QPalette.Active, QPalette.Mid, brush12)
        palette10.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette10.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette10.setBrush(QPalette.Active, QPalette.ButtonText, brush2)
        palette10.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette10.setBrush(QPalette.Active, QPalette.Window, brush8)
        palette10.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette10.setBrush(QPalette.Active, QPalette.AlternateBase, brush11)
        palette10.setBrush(QPalette.Active, QPalette.ToolTipBase, brush7)
        palette10.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
        palette10.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette10.setBrush(QPalette.Inactive, QPalette.Button, brush8)
        palette10.setBrush(QPalette.Inactive, QPalette.Light, brush9)
        palette10.setBrush(QPalette.Inactive, QPalette.Midlight, brush10)
        palette10.setBrush(QPalette.Inactive, QPalette.Dark, brush11)
        palette10.setBrush(QPalette.Inactive, QPalette.Mid, brush12)
        palette10.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette10.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette10.setBrush(QPalette.Inactive, QPalette.ButtonText, brush2)
        palette10.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette10.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette10.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette10.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush11)
        palette10.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush7)
        palette10.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush6)
        palette10.setBrush(QPalette.Disabled, QPalette.WindowText, brush11)
        palette10.setBrush(QPalette.Disabled, QPalette.Button, brush8)
        palette10.setBrush(QPalette.Disabled, QPalette.Light, brush9)
        palette10.setBrush(QPalette.Disabled, QPalette.Midlight, brush10)
        palette10.setBrush(QPalette.Disabled, QPalette.Dark, brush11)
        palette10.setBrush(QPalette.Disabled, QPalette.Mid, brush12)
        palette10.setBrush(QPalette.Disabled, QPalette.Text, brush11)
        palette10.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette10.setBrush(QPalette.Disabled, QPalette.ButtonText, brush11)
        palette10.setBrush(QPalette.Disabled, QPalette.Base, brush8)
        palette10.setBrush(QPalette.Disabled, QPalette.Window, brush8)
        palette10.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        palette10.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush8)
        palette10.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush7)
        palette10.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush6)
        self.lbl_peso.setPalette(palette10)
        self.lbl_peso.setFont(font1)
        self.sp_Peso = QSpinBox(self.centralwidget)
        self.sp_Peso.setObjectName(u"sp_Peso")
        self.sp_Peso.setGeometry(QRect(150, 450, 81, 31))
        self.sp_Peso.setMaximum(350)
        self.btn_peso = QPushButton(self.centralwidget)
        self.btn_peso.setObjectName(u"btn_peso")
        self.btn_peso.setGeometry(QRect(390, 450, 151, 31))
        self.lbl_fecha_nac = QLabel(self.centralwidget)
        self.lbl_fecha_nac.setObjectName(u"lbl_fecha_nac")
        self.lbl_fecha_nac.setGeometry(QRect(10, 510, 151, 20))
        palette11 = QPalette()
        palette11.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette11.setBrush(QPalette.Active, QPalette.Button, brush8)
        palette11.setBrush(QPalette.Active, QPalette.Light, brush9)
        palette11.setBrush(QPalette.Active, QPalette.Midlight, brush10)
        palette11.setBrush(QPalette.Active, QPalette.Dark, brush11)
        palette11.setBrush(QPalette.Active, QPalette.Mid, brush12)
        palette11.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette11.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette11.setBrush(QPalette.Active, QPalette.ButtonText, brush2)
        palette11.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette11.setBrush(QPalette.Active, QPalette.Window, brush8)
        palette11.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette11.setBrush(QPalette.Active, QPalette.AlternateBase, brush11)
        palette11.setBrush(QPalette.Active, QPalette.ToolTipBase, brush7)
        palette11.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
        palette11.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette11.setBrush(QPalette.Inactive, QPalette.Button, brush8)
        palette11.setBrush(QPalette.Inactive, QPalette.Light, brush9)
        palette11.setBrush(QPalette.Inactive, QPalette.Midlight, brush10)
        palette11.setBrush(QPalette.Inactive, QPalette.Dark, brush11)
        palette11.setBrush(QPalette.Inactive, QPalette.Mid, brush12)
        palette11.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette11.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette11.setBrush(QPalette.Inactive, QPalette.ButtonText, brush2)
        palette11.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette11.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette11.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette11.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush11)
        palette11.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush7)
        palette11.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush6)
        palette11.setBrush(QPalette.Disabled, QPalette.WindowText, brush11)
        palette11.setBrush(QPalette.Disabled, QPalette.Button, brush8)
        palette11.setBrush(QPalette.Disabled, QPalette.Light, brush9)
        palette11.setBrush(QPalette.Disabled, QPalette.Midlight, brush10)
        palette11.setBrush(QPalette.Disabled, QPalette.Dark, brush11)
        palette11.setBrush(QPalette.Disabled, QPalette.Mid, brush12)
        palette11.setBrush(QPalette.Disabled, QPalette.Text, brush11)
        palette11.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette11.setBrush(QPalette.Disabled, QPalette.ButtonText, brush11)
        palette11.setBrush(QPalette.Disabled, QPalette.Base, brush8)
        palette11.setBrush(QPalette.Disabled, QPalette.Window, brush8)
        palette11.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        palette11.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush8)
        palette11.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush7)
        palette11.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush6)
        self.lbl_fecha_nac.setPalette(palette11)
        self.lbl_fecha_nac.setFont(font1)
        self.de_fecha_nac = QDateEdit(self.centralwidget)
        self.de_fecha_nac.setObjectName(u"de_fecha_nac")
        self.de_fecha_nac.setGeometry(QRect(180, 510, 110, 22))
        self.de_fecha_nac.setMaximumDateTime(QDateTime(QDate(2023, 8, 15), QTime(23, 59, 59)))
        self.txt_carrera = QLineEdit(self.centralwidget)
        self.txt_carrera.setObjectName(u"txt_carrera")
        self.txt_carrera.setGeometry(QRect(150, 340, 241, 41))
        self.txt_carrera.setMaxLength(100)
        self.lbl_carrera = QLabel(self.centralwidget)
        self.lbl_carrera.setObjectName(u"lbl_carrera")
        self.lbl_carrera.setGeometry(QRect(40, 350, 71, 16))
        palette12 = QPalette()
        palette12.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette12.setBrush(QPalette.Active, QPalette.Button, brush8)
        palette12.setBrush(QPalette.Active, QPalette.Light, brush9)
        palette12.setBrush(QPalette.Active, QPalette.Midlight, brush10)
        palette12.setBrush(QPalette.Active, QPalette.Dark, brush11)
        palette12.setBrush(QPalette.Active, QPalette.Mid, brush12)
        palette12.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette12.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette12.setBrush(QPalette.Active, QPalette.ButtonText, brush2)
        palette12.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette12.setBrush(QPalette.Active, QPalette.Window, brush8)
        palette12.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette12.setBrush(QPalette.Active, QPalette.AlternateBase, brush11)
        palette12.setBrush(QPalette.Active, QPalette.ToolTipBase, brush7)
        palette12.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
        palette12.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette12.setBrush(QPalette.Inactive, QPalette.Button, brush8)
        palette12.setBrush(QPalette.Inactive, QPalette.Light, brush9)
        palette12.setBrush(QPalette.Inactive, QPalette.Midlight, brush10)
        palette12.setBrush(QPalette.Inactive, QPalette.Dark, brush11)
        palette12.setBrush(QPalette.Inactive, QPalette.Mid, brush12)
        palette12.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette12.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette12.setBrush(QPalette.Inactive, QPalette.ButtonText, brush2)
        palette12.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette12.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette12.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette12.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush11)
        palette12.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush7)
        palette12.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush6)
        palette12.setBrush(QPalette.Disabled, QPalette.WindowText, brush11)
        palette12.setBrush(QPalette.Disabled, QPalette.Button, brush8)
        palette12.setBrush(QPalette.Disabled, QPalette.Light, brush9)
        palette12.setBrush(QPalette.Disabled, QPalette.Midlight, brush10)
        palette12.setBrush(QPalette.Disabled, QPalette.Dark, brush11)
        palette12.setBrush(QPalette.Disabled, QPalette.Mid, brush12)
        palette12.setBrush(QPalette.Disabled, QPalette.Text, brush11)
        palette12.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette12.setBrush(QPalette.Disabled, QPalette.ButtonText, brush11)
        palette12.setBrush(QPalette.Disabled, QPalette.Base, brush8)
        palette12.setBrush(QPalette.Disabled, QPalette.Window, brush8)
        palette12.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        palette12.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush8)
        palette12.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush7)
        palette12.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush6)
        self.lbl_carrera.setPalette(palette12)
        self.lbl_carrera.setFont(font1)
        self.btn_cal_edad = QPushButton(self.centralwidget)
        self.btn_cal_edad.setObjectName(u"btn_cal_edad")
        self.btn_cal_edad.setGeometry(QRect(390, 510, 151, 31))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(220, 10, 191, 61))
        palette13 = QPalette()
        palette13.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette13.setBrush(QPalette.Active, QPalette.Button, brush13)
        palette13.setBrush(QPalette.Active, QPalette.Light, brush14)
        palette13.setBrush(QPalette.Active, QPalette.Midlight, brush15)
        palette13.setBrush(QPalette.Active, QPalette.Dark, brush16)
        palette13.setBrush(QPalette.Active, QPalette.Mid, brush17)
        palette13.setBrush(QPalette.Active, QPalette.Text, brush6)
        palette13.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette13.setBrush(QPalette.Active, QPalette.ButtonText, brush6)
        palette13.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette13.setBrush(QPalette.Active, QPalette.Window, brush13)
        palette13.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette13.setBrush(QPalette.Active, QPalette.AlternateBase, brush18)
        palette13.setBrush(QPalette.Active, QPalette.ToolTipBase, brush7)
        palette13.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
        palette13.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette13.setBrush(QPalette.Inactive, QPalette.Button, brush13)
        palette13.setBrush(QPalette.Inactive, QPalette.Light, brush14)
        palette13.setBrush(QPalette.Inactive, QPalette.Midlight, brush15)
        palette13.setBrush(QPalette.Inactive, QPalette.Dark, brush16)
        palette13.setBrush(QPalette.Inactive, QPalette.Mid, brush17)
        palette13.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        palette13.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette13.setBrush(QPalette.Inactive, QPalette.ButtonText, brush6)
        palette13.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette13.setBrush(QPalette.Inactive, QPalette.Window, brush13)
        palette13.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette13.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush18)
        palette13.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush7)
        palette13.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush6)
        palette13.setBrush(QPalette.Disabled, QPalette.WindowText, brush16)
        palette13.setBrush(QPalette.Disabled, QPalette.Button, brush13)
        palette13.setBrush(QPalette.Disabled, QPalette.Light, brush14)
        palette13.setBrush(QPalette.Disabled, QPalette.Midlight, brush15)
        palette13.setBrush(QPalette.Disabled, QPalette.Dark, brush16)
        palette13.setBrush(QPalette.Disabled, QPalette.Mid, brush17)
        palette13.setBrush(QPalette.Disabled, QPalette.Text, brush16)
        palette13.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette13.setBrush(QPalette.Disabled, QPalette.ButtonText, brush16)
        palette13.setBrush(QPalette.Disabled, QPalette.Base, brush13)
        palette13.setBrush(QPalette.Disabled, QPalette.Window, brush13)
        palette13.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        palette13.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush13)
        palette13.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush7)
        palette13.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush6)
        self.label.setPalette(palette13)
        font3 = QFont()
        font3.setFamilies([u"Forte"])
        font3.setPointSize(28)
        font3.setUnderline(True)
        self.label.setFont(font3)
        vtn_principal.setCentralWidget(self.centralwidget)
        self.mnb_menu_principal = QMenuBar(vtn_principal)
        self.mnb_menu_principal.setObjectName(u"mnb_menu_principal")
        self.mnb_menu_principal.setGeometry(QRect(0, 0, 619, 23))
        vtn_principal.setMenuBar(self.mnb_menu_principal)
        self.stb_estado = QStatusBar(vtn_principal)
        self.stb_estado.setObjectName(u"stb_estado")
        vtn_principal.setStatusBar(self.stb_estado)

        self.retranslateUi(vtn_principal)

        QMetaObject.connectSlotsByName(vtn_principal)
    # setupUi

    def retranslateUi(self, vtn_principal):
        self.lbl_nombre.setText(QCoreApplication.translate("vtn_principal", u"Nombre:", None))
        self.lbl_apellido.setText(QCoreApplication.translate("vtn_principal", u"Apellido:", None))
        self.btn_grabar.setText(QCoreApplication.translate("vtn_principal", u"Grabar ", None))
        self.cb_tipo_persona.setItemText(0, QCoreApplication.translate("vtn_principal", u"Estudiante", None))
        self.cb_tipo_persona.setItemText(1, QCoreApplication.translate("vtn_principal", u"Docente", None))

        self.lbl_tipo_persona.setText(QCoreApplication.translate("vtn_principal", u"Tipo:", None))
        self.lbl_email.setText(QCoreApplication.translate("vtn_principal", u"Email:", None))
        self.lbl_Cedula.setText(QCoreApplication.translate("vtn_principal", u"Cedula:", None))
        self.btn_buscar_cedula.setText(QCoreApplication.translate("vtn_principal", u"BUSCAR POR CEDULA", None))
        self.lbl_estatura.setText(QCoreApplication.translate("vtn_principal", u"Estatura (cm):", None))
        self.btn_estatura.setText(QCoreApplication.translate("vtn_principal", u" Estadistica_Estatura", None))
        self.lbl_peso.setText(QCoreApplication.translate("vtn_principal", u"Peso (libras):", None))
        self.btn_peso.setText(QCoreApplication.translate("vtn_principal", u" Estadistica_Peso", None))
        self.lbl_fecha_nac.setText(QCoreApplication.translate("vtn_principal", u"Fecha_Nacimiento:", None))
        self.txt_carrera.setText("")
        self.lbl_carrera.setText(QCoreApplication.translate("vtn_principal", u"Carerra:", None))
        self.btn_cal_edad.setText(QCoreApplication.translate("vtn_principal", u" Calculo_Edades", None))
        self.label.setText(QCoreApplication.translate("vtn_principal", u"GRUPO 9", None))
        pass
    # retranslateUi

